name: Welcome Collaborator

on:
  push:
    branches:
      - branch2

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to Collaborator
        run: echo "Hello, ${{ github.actor }} 👋"
